# See https://taskfile.dev/
#
# e.g. `task -w test-cov`
version: "3"

tasks:
  build:
    cmds:
      - go build -o ./build/rfc3339
    sources:
      - "**/*.go"

  test:
    cmds:
      - go test ./...
    sources:
      - "**/*.go"

  test-cov:
    cmds:
      - go test -cover ./...
    sources:
      - "**/*.go"

  test-cov-html:
    cmds:
      - go test -coverprofile=./build/coverage.out ./...
      - go tool cover -html=./build/coverage.out -o ./build/coverage.html
    sources:
      - "**/*.go"
